### ISSUE TITLE
unmaintained

### ISSUE THREAD

**Issue by miquelmasrieramrf** [AngelMariages/RodaliesWidget#121]
trabaja cabron!

**Comment by miquelmasrieramrf** [comment]
<img width="501" alt="Screen Shot 2019-07-25 at 1 10 20 PM" src="https://user-images.githubusercontent.com/20967825/61870412-5abfc200-aede-11e9-871b-58f44e618a13.png">

**Comment by oscard0m** [comment]
Hi @AngelMariages,

I still would like to enjoy your awesome widget. Is there any roadmap or plan for it?

Thanks

**Comment by miquelmasrieramrf** [comment]
<img width="246" alt="Screen Shot 2019-07-25 at 1 18 34 PM" src="https://user-images.githubusercontent.com/20967825/61870575-bab66880-aede-11e9-9a1b-2f069c0e84ce.png">

**Comment by angelmariagesmrf** [comment]
I would like to announce that thanks to the collaboration of Rosalia in this project, we're going to sell it to Google and make us milloniarias.

**Comment by miquelmasrieramrf** [comment]
this project is TRÁ TRÁsh
